### ISSUE TITLE
Packet loss under high load conditions

### ISSUE THREAD

**Issue by josemic** [msantos/epcap#18]
Finally I got the stream parser of josemic/enose working (under Ubuntu). It tracks the TCP sequence numbers against acknowledge numbers of TCP connections. (The code will be on Github soon.)

It uses Epcap to capture the packets. Under normal load conditions around 80% (according to Erlang observer) there is no packet loss, which is great.

Under high load conditions, when the load reaches 100% for a short time, instead of the Erlang VM queueing the messages, the messages get lost. The packages are still dumped into tcpdump. Epcap/Erlang, however does not seem to get these messages. The results is that enose loosing sequence and indicates failures. Logs have shown that about 26 subsequent packages were lost by Epcap.

Note:
No packet loss occurs if Epcap/enose is run from Pcap file, even if the load gets long time to 100%.

There are multiple solutions to this problem:
- Under high load conditions, drop packets and indicate packet loss. Helpful would be, if additional information such as the sender / receiver IP addresses could be provided.
- Fix the packet loss and deal with the issue inside Erlang. (Any ides how to get Erlang VM load data from inside Erlang.)

**Comment by ates** [comment]
I think it's ok to close this issue. Michael, do you have objections?

**Comment by msantos** [comment]
Agreed, thanks @ates !

**Comment by josemic** [comment]
I think that closing is fine, unless someone runs into performance problems. Still I'd like to draw a conclusion here.

>If my suspicions are correct, to solve it, well, the simplest way is to either run more epcap ports or run more nodes over distribution. 
Assume you want to filter all packets passing on eth0:

`sniff:start([{interface, "eth0"}]).`

Assume the throughput is not sufficient: 
There is currently no way to move the first half of the packets to Erlang node instance 1 and the second half of the packets to Erlang node instance 2. With the current epcap configuration options there is no way to do this in a generic way.

> While it should be possible to divide up the rules amongst epcap ports so IP addresses are constant, 

I would even go further and assume the quadruple of SourceIPAddress, SourcePort, DestinationIPAddress, DestinationPort is constant, as this will provide a better distribution of the traffic to the Erlang nodes and will remain constant for the lifetime any given traffic.

>I guess you mean moving IP addresses between running epcap instances? 
No. Just thought of a static configuration. 

> Like adjusting the pcap expression on the fly? Can't think of a way to do that, that would not drop packets.
Moving them will usually break the application layer (the application using epcap), as a connection started will no longer be stopped on the same node. Thus dynamic arrangement might not be useful - or only useful for newly setup connections. Not sure that dynamic arrangement would be useful.

Lets assume you want to run on a N-core system N-Erlang nodes to distribute the incoming traffic evenly based on e.g. the formula:
`n = ((SourceIPAddress mod N)+ (SourcePort mod N) + (DestinationIPAddress mod N) + (DestinationPort mod N)) mod N`

Where N is the number of Erlang instances to be used, n is the current Erlang instance and IPAddress mod N is defined for IP4 and IP6 Address as the following:

```
Ip_address = Ip4_address or Ip6_address
Ip4_address 
= {0..255, 0..255, 0..255, 0..255} 
= {Addr4_3, Addr4_2, Addr4_1, Addr4_0} 

Ip4_address mod N 
= {Addr4_3, Addr4_2, Addr4_1, Addr4_0}  mod N 
= ((Addr4_3 mod N) + (Addr4_2 mod N) + (Addr4_1 mod N) + (Addr4_0 mod N)) mod N

Ip6_address
  = {0..65535, 0..65535, 0..65535, 0..65535, 0..65535, 0..65535, 0..65535, 0..65535}
  = {Addr6_7, Addr6_6, Addr6_5, Addr6_4, Addr6_3, Addr6_2, Addr6_1, Addr6_0}

Ip6_address mod N
= {Addr6_7, Addr6_6, Addr6_5, Addr6_4, Addr6_3, Addr6_2, Addr6_1, Addr6_0} mod N
=  ((Addr6_7 mod N) + (Addr6_6 mod N) + (Addr6_5 mod N) + (Addr6_4 mod N)
    + (Addr6_3 mod N) + (Addr6_2 mod N) + (Addr6_1 mod N) + (Addr6_0 mod N)) mod N
```

Something like below could be used to start N epcap instances on N-nodes:

```
erl -name 'epcapnode0'
sniff:start([{interface, "eth0"}, {instance, 0, N}]). 

erl -name 'epcapnode1'
sniff:start([{interface, "eth0"}, {instance, 1, N}]).
...

erl -name 'epcapnodeN-1'
sniff:start([{interface, "eth0"}, {instance, N-1, N}]).
```

and filter out the n-th fraction of the incoming traffic to the Erlang node n using the formula above.
